import Head from 'next/head'
import { useRouter } from 'next/router'
import styled from 'styled-components'
import Header from '../Header'
import Footer from '../Footer'
import LightHalo from './LightHalo'

const StyleMain = styled.main`
  min-height: 100vh;
  padding-top: 40px;

  @media (min-width: ${({ theme }) => theme.breakPiont.md}) {
    padding-top: 46px;
  }

  @media (min-width: ${({ theme }) => theme.breakPiont.lg}) {
    padding-top: 70px;
  }
`

const Layout = ({ children }) => {
  const router = useRouter()
  let pathname = 'Create Next App'

  if (router.pathname === '/') {
    pathname = 'Home'
  }
  if (router.pathname.includes('/ourvision')) {
    pathname = 'Our Vision'
  }
  if (router.pathname.includes('/ourbusiness')) {
    pathname = 'Our Business'
  }
  if (router.pathname.includes('/ourworks')) {
    pathname = 'Our Works'
  }
  if (router.pathname.includes('/ourupdates')) {
    pathname = 'Our Updates'
  }
  if (router.pathname.includes('/contactus')) {
    pathname = 'Contact Us'
  }

  return (
    <>
      <Head>
        <title>{pathname}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200;0,400;0,600;0,700;0,800;0,900;1,200;1,400;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <LightHalo>
        <StyleMain>{children}</StyleMain>
      </LightHalo>
      <Footer />
    </>
  )
}

export default Layout
