import Head from 'next/head'
import { useRouter } from 'next/router'
import Header from './Header'
import Footer from './Footer'
import styled from 'styled-components'

const LayoutSection = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 50vh;
`;

const Layout = ({children}) => {
  const router = useRouter();
  let pathname = '';
  
  switch(router.pathname){
    case '/':
      pathname = 'Home'
      break;
    case '/about':
      pathname = 'About'
      break;
    case '/contact':
      pathname = 'Contact'
      break;
    default:
      pathname = 'Create Next App'
    }
          
  return (
    <>
      <Head>
        <title>{pathname}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LayoutSection>
        {children}
      </LayoutSection>
      <Footer />
    </>
  )
}

export default Layout
